### ISSUE TITLE
neovim support

### ISSUE THREAD

**Issue by paulondc** [skywind3000/vim-quickui#1]
Do you have any plans to support [neovim](https://github.com/neovim/neovim) ?

I tried your plugin with the latest stable neovim version (0.4.3) and got the following errors (for context I was trying to run the sample code):

```
Error detected while processing function quickui#menu#open[5]..quickui#menu#create:
line   15:
E117: Unknown function: popup_create
E15: Invalid expression: popup_create([s:cmenu.inst.text], {'hidden':1, 'wrap':0})
line   16:
E121: Undefined variable: winid
E116: Invalid arguments for function winbufnr
E15: Invalid expression: winbufnr(winid)
line   17:
E121: Undefined variable: winid
E15: Invalid expression: winid
line   18:
E121: Undefined variable: bufnr
E15: Invalid expression: bufnr
line   24:
E121: Undefined variable: winid
E116: Invalid arguments for function popup_move
line   25:
E121: Undefined variable: winid
E116: Invalid arguments for function setwinvar
...
```

**Comment by skywind3000** [comment]
It doesn't support neovim yet, I need time to study neovim's floating window apis.

**Comment by paulondc** [comment]
I assume what works in vim is going to work in neovim (since it's a drop-in replacement). However, this is a special kind since this is a new api in vim for something that was already support in neovim. Therefore, would you mind to add a notice in the README.md telling that this plugin currently does not work in neovim. Thank you

**Comment by skywind3000** [comment]
updated

**Comment by skywind3000** [comment]
good news, neovim is supported now.

**Comment by paulondc** [comment]
I've tested it in neovim 0.4.3 and it's working like a charm!

Thank you
