### ISSUE TITLE
Can't change relativenumber in current buffer

### ISSUE THREAD

**Issue by LinArcX** [skywind3000/vim-quickui#10]
Hi. i want to change relative number option in current buffer. So, tried this is my last try:
```
....
\ [ "relati&ve number %{&relativenumber? 'OFF':'ON'}", ':set relativenumber!' ],
....
```
But it won't work.
Edit: This line is a part of `call quickui#menu#install()`.

**Comment by skywind3000** [comment]
I can't reproduce your issue, it works in my laptop.

**Comment by LinArcX** [comment]
Oh, sorry. My mistake. I actually had this lines at the end of __init.vim__:
```
"" Enable relative/absolute line numbers
"augroup numbertoggle
"    autocmd!
"    autocmd BufEnter,FocusGained,InsertLeave * set relativenumber
"    autocmd BufLeave,FocusLost,InsertEnter   * set norelativenumber
"augroup END
```
Delete them and now everything works.
