### ISSUE TITLE
Can't see menu in different file types

### ISSUE THREAD

**Issue by LinArcX** [skywind3000/vim-quickui#13]
Hi. i have a menu [in my local .nvimrc file](https://github.com/LinArcX/learning_cmake/blob/master/.nvimrc#L26)

But it only opens when I'm inside a **.cpp** or **.hpp** file. I want for example see this menu in **.txt**, **.md** or other file extensions too.

**Comment by LinArcX** [comment]
Oh, my mistake. I defined another menu and forgot ro remove it:
https://github.com/LinArcX/learning_cmake/blob/master/.nvimrc#L56

**Comment by skywind3000** [comment]
recommendation:

use a separated context menu for different file types and bind it to `K`:

![图片](https://user-images.githubusercontent.com/3035071/74662043-1fffdd00-51d4-11ea-9270-269218889a52.png)

https://github.com/skywind3000/vim/blob/2e3e9878d83731c656db655ff5f6dac548a8daab/plugin/menu_init.vim#L165-L190
