### ISSUE TITLE
after loading a new colorscheme, the highlight will disappear.

### ISSUE THREAD

**Issue by Freed-Wu** [skywind3000/vim-quickui#35]
this is a test.vim
```{.vim}
if !has('nvim')
	set nocompatible
endif
set runtimepath +=$GITHUBWORKSPACE/skywind3000/vim-quickui
	let g:quickui_show_tip = 1
	call quickui#menu#reset()
	call quickui#menu#install('Pla&y', [
				\ ['--', ''],
				\ ['Eas&y', 'SudokuEasy'],
				\ ['Medi&um', 'SudokuMedium'],
				\ ['Har&d', 'SudokuHard'],
				\ ['&VeryHard', 'SudokuVeryHard'],
				\ ])
```

then `gvim -u test.vim`
![image](https://user-images.githubusercontent.com/32936898/82874407-7e252480-9f68-11ea-8820-df0ff59acfdd.png)
`colorscheme default`
![image](https://user-images.githubusercontent.com/32936898/82874447-8d0bd700-9f68-11ea-8852-0019f23af624.png)

thanks!

**Comment by Freed-Wu** [comment]
by now, i use the following temporary solution:

```{.vim}
autocmd Colorscheme * call QuickThemeChange(get(g:, 'quickui_color_scheme', ''))
```

add this code to vimrc can avoid this problem.
perhaps add it to `vim-quickui/plugin/quickui.vim` will be better?

**Comment by arozehnal** [comment]
OS AIX 7.2
VIM 9.0, quickui_version = '1.4.3'
TERM=xterm-256color
same trouble
