### ISSUE TITLE
how to select a command without hitting <enter> ?

### ISSUE THREAD

**Issue by lsaint** [skywind3000/vim-quickui#36]
Just like in normal mode, input `:xxx -a -b -c  (something_i_want_to_input_dynamically)`

When i select an item from quickui#menu#,  is there a way to just show `:xxx -a -b -c ` at the bottom and let me input something else  dynamically then hit _enter_ manually?

**Comment by neolao** [comment]
how did you solved the issue? I want to do the thing as you described

**Comment by neolao** [comment]
I created a function with an input:

```vim
function! SearchInFiles()
  let searchTerm = input('Search in files: ')
  execute "CtrlSF " searchTerm
endfunction

call quickui#menu#install('mYmenu', [
  \ [ "Test", ':call SearchInFiles()' ],
\ ])
```

**Comment by lsaint** [comment]
```
call quickui#menu#install("mYmenu", [
    \ [ "Test", 'exec input("", ":call SearchInFiles()")'],
\ ])
```
