### ISSUE TITLE
How to execute commands that we can only use them in normal mode?

### ISSUE THREAD

**Issue by LinArcX** [skywind3000/vim-quickui#6]
I'm using [coc.nvim](https://github.com/neoclide/coc.nvim) as Intellisense engine for neovim. I want to use **vim-quickui** to remap it's functionalities:
https://github.com/neoclide/coc.nvim#example-vim-configuration

But most of it's command only execute in normal mode:
https://github.com/neoclide/coc.nvim/blob/master/doc/coc.txt#L663

My question is how configure **vim-quickui** to execute **coc.nvim** commands. Imagin i have this menu:
```
call quickui#menu#install('C&oc', [
            \ [ "&config", 'CocConfig' ],
            \ [ "code-&action", '<Plug>(coc-codeaction)' ],
            \ [ "codeaction-&selected", '<Plug>(coc-codeaction-selected)' ],
            \ [ "co&mmand", '<Plug>(coc-command)' ],
            \ [ "dia&gnostics", '<Plug>(coc-diagnostics)' ],
 \ ])
```

But it won't works and gives me this error:
> Error detected while processing function quickui#menu#open[8]..quickui#menu#nvim_open_menu:                                                            
line   94:                                                                                                                                             
E488: Trailing characters: <Plug>(coc-command)                                                                                                         
Press ENTER or type command to continue

**Comment by skywind3000** [comment]
I don't use coc, try:

```VimL
[ "code-&action", 'normal "\<Plug>(coc-codeaction)"' ],
```

**Comment by LinArcX** [comment]
It works! thank you.

**Comment by skywind3000** [comment]
Great, good for you !
