### ISSUE TITLE
Buffer switcher能否引入MRU排序？

### ISSUE THREAD

**Issue by qiushihao** [skywind3000/vim-quickui#64]
正在用Buffer switcher替代MiniBufferExplorer和unite，不知道有没有计划引入两个全局参数。
一个用来控制buffer的排序，按照most recently used的时间顺序来排序；
另一个用来控制buffer显示的个数，这样当有很多数量的buffer之后，可以按照最近访问的顺序只显示最近使用的几个。

**Comment by skywind3000** [comment]
可以考虑啊
