### ISSUE TITLE
怎么设置cursor？

### ISSUE THREAD

**Issue by JimmyHuang454** [skywind3000/vim-quickui#66]
似乎quickui没有对cursor进行封装，就是vim中的firstline和nvim中的nvim_win_set_cursor()

这个功能很常用，例如在preview中，直接跳到指定的行，而不是只显示第一行。

我试了试   ` call quickui#core#win_execute(l:win_id, 'call cursor(20, 1)') ` 没有效果

**Comment by skywind3000** [comment]
最新的统一接口是这个：
https://github.com/skywind3000/vim-quickui/blob/master/autoload/quickui/window.vim 

把 popup/floatwin 的常见操作全部抽象统一了。

例子是：
https://github.com/skywind3000/vim-quickui/blob/master/test/test_window.vim

使用场景是：
https://github.com/skywind3000/vim-quickui/blob/master/autoload/quickui/confirm.vim

后面控件都会基于 window.vim 封装的 window 类来开发。
