### ISSUE TITLE
can't open menu/popups -> invalid key 'noautocmd'

### ISSUE THREAD

**Issue by sagiegurari** [skywind3000/vim-quickui#68]
Amazing plugin. having been using it for a long time.
However, this week I updated it (didn't update it for months) and it started failing when i open a menu:

```
Error detected while processing function _menu_open_async[4]..quickui#menu#open[8]..quickui#menu#nvim_open_menu:
line 31:
E5555: API call: Invalid key 'noautocmd'
```

_menu_open_async is called from a timer and just does the following:

```
call quickui#menu#open()
```

nvim version:

```
NVIM v0.5.0-dev+1022-g77a6049e0
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```

**Comment by skywind3000** [comment]
because `noautocmd` is a valid option introduced in nvim 0.5.0 stable:

![image](https://user-images.githubusercontent.com/3035071/151711119-82e26eb2-fb8b-45b7-b6b6-9a6f5a5f3891.png)

You are using a very old 0.5 **dev** version,

fixed in the latest version

**Comment by skywind3000** [comment]
please try the latest version, I have changed:

    if has('nvim-0.5.0')

to 

    if has('nvim-0.6.0')

**Comment by sagiegurari** [comment]
ya that fixed it, thanks a lot. Your plugin is so useful.
i'll also upgrade my neovim :D
