### ISSUE TITLE
Is it possible to show help contents in textbox?

### ISSUE THREAD

**Issue by LinArcX** [skywind3000/vim-quickui#7]
You have a sample code [here](https://github.com/skywind3000/vim-quickui#textbox) that shows the usage of using textbox. I'm curious to know is it possible to show the content of help windows(like `:help index`) in textbox?

**Comment by skywind3000** [comment]
Impossible for `:help xxx`, but I made a function to run external shell commands, and display the result in the `textbox`:

```VimL
call quickui#textbox#command(command, opts)
```

see:

https://github.com/skywind3000/vim-quickui/blob/c03f59da6395bca0ee87aaf75dee9a62e8e327fa/autoload/quickui/tools.vim#L188

**Comment by LinArcX** [comment]
Yes, it works. But it'll be better to have an option for search in textbox content.(/ or ?)
Right now if i'm not mistaken we can only scroll the content.

**Comment by skywind3000** [comment]
There will be.

**Comment by skywind3000** [comment]
I forget that it already accept `/` or `?` and `:` command in textbox.

**Comment by skywind3000** [comment]
I have figured a way to display `:h index` in the textbox, try this:

```VimL
call quickui#textbox#open(readfile(expand('$VIMRUNTIME/doc/index.txt')), {'syntax':'help','color':'Normal'})
```

**Comment by skywind3000** [comment]
I made a function for you:

```VimL
call quickui#tools#display_help("stridx()")
```

**Comment by LinArcX** [comment]
Wow! wow. Awesome. Thank you so much.
