### ISSUE TITLE
How to get persistent menu?

### ISSUE THREAD

**Issue by profallgood** [skywind3000/vim-quickui#72]
Is there a way to have the menu persist and load automatically? I've got it bound to F10 right now and I was able to get it to startup, but essentially it doesn't persist at all and stay like in some more conventional editors.

**Comment by skywind3000** [comment]
The top line is reserved in vim for `tabline`. quickui can use it temporarily, but cannot occupy it forever.

**Comment by profallgood** [comment]
> 

Thanks!

Is there a way to modify it so it appears BELOW the tabline?

**Comment by skywind3000** [comment]
same problem, the second line will overshadow the text.

**Comment by profallgood** [comment]
I guess putting it above the tabar line is out of the question too unless you hacked VIM to get you that extra space eh?

**Comment by skywind3000** [comment]
yeah
