### ISSUE TITLE
How to make main menu always visible

### ISSUE THREAD

**Issue by TamaMcGlinn** [skywind3000/vim-quickui#73]
I'm looking for a way to make a permanent, always visible main menu. Has anyone done this before with quickui?

If I were to add some sort of aucmd that reopens the menu whenever it closes, there would still be two problems:
- the first line of the file is obscured by the menu, instead the file should be shifted down 1 line
- some keybindings would need to be disabled, as hjkl for instance are needed in the file buffer to do things; I only intend the menu to be useable with the mouse

If I can figure this out, it will become an option, so as not to change the (normally much saner) current behaviour. However, I am trying to create a configuration specifically for beginners aged 7 and up; the less needs to be remembered, the better.

**Comment by skywind3000** [comment]
similar to https://github.com/skywind3000/vim-quickui/issues/72
