### ISSUE TITLE
quickui_border_style = 2时，显示异常

### ISSUE THREAD

**Issue by VimWei** [skywind3000/vim-quickui#84]
正常的情形：let g:quickui_border_style = 1

![image](https://github.com/skywind3000/vim-quickui/assets/25874852/96140cd4-bed7-4292-a117-3eaf47c0da08)

异常的情形：let g:quickui_border_style = 2

![image](https://github.com/skywind3000/vim-quickui/assets/25874852/25cc391d-cf71-4c75-91e9-c9e73289934a)

**Comment by skywind3000** [comment]
你的字体异常，一个字符宽度的横线被当成了两个字符宽度，你看两个挨着的横线字符中间空隙都接不起来

**Comment by VimWei** [comment]
" set ambiwidth=double

原来是这一句造成的。
